name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]
  workflow_dispatch:


jobs:
  pypi-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for PyPI OIDC Trusted Publishing (passwordless)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build distribution package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
